@startuml
autonumber


title FNV2 China Device Registration

participant "Device Registration Regionalizer NA" as drr
participant "Assets Service NA" as assets
participant "MQTT Credentials Manager NA" as credman
participant "SyncP Service NA" as syncp
participant "Inventory API CN" as inv

[-> drr: Device Registered

drr -> assets ++: RetrieveAsset
return AssetMetadata

drr -> credman ++: ExportMqttCredentials 
return MqttCredentials

drr -> syncp ++: ExportSyncPKeys
return WrappedSyncPKeys

drr -> inv ++: RegisterDevice
return DeviceRegistrationResponse
@enduml