@startuml
autonumber

title FNV2 Provisioning

participant "MQTT Provisioning" as mp
participant "MQTT Provisioning Ingest" as mi
participant "FTCP Ingest" as fi
participant "FTCP Decrypter" as fd
participant "Module Registration Processor (MoRP)" as mo
participant "Workflow Processing Engine" as wpe
participant "Assets" as assets
participant "IAM" as iam
participant "CMS" as cms
participant "MQTT Outbound" as mqo
participant "Cloud to FTCP Converter" as ctftcp
participant "CMS" as cms

mp -> mi: Incoming MQTT Provisioning Message
mi ->> fi: Produce to provisioning-feed-ingest
fi ->> fd: Produce to ftcp-ingest-provision
fd ->> mo: Produce to ftcp-ingest-processed-provision
mo ->> wpe ++: Vehicle Registration Event
wpe -> assets: Upsert Vehicle
wpe -> assets: Bind Device to Vehicle
wpe -> assets: Update Asset Tags
wpe -> iam: Add Vehicle Permissions
return Workflow Success Event
mo -> ctftcp: Send Provisioning Alert Response
mo -> cms: Send CHURL Command
@enduml
