@startuml
hide empty description
[*] --> REQUESTED: Provisioning Data Requested
REQUESTED --> REQUEST_DELIVERY_QUEUED: Delivery Queued

REQUEST_DELIVERY_QUEUED --> REQUEST_DELIVERY_IN_PROGRESS: Device Connected to Cloud

REQUEST_DELIVERY_IN_PROGRESS --> AWAITING_PROVISIONING_DATA_REQUEST_COMMAND_RESPONSE: Queued on Device
AWAITING_PROVISIONING_DATA_REQUEST_COMMAND_RESPONSE --> SUCCESS: Response Received
@enduml